/*
 * generated by Xtext 2.22.0
 */
package web;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CertifiedDjikstraLanguageStandaloneSetup extends CertifiedDjikstraLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new CertifiedDjikstraLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
