/*
 * generated by Xtext 2.19.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CertifiedDjikstraLanguageStandaloneSetup extends CertifiedDjikstraLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new CertifiedDjikstraLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
