/*
 * generated by Xtext 2.19.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.CertifiedDjikstraLanguageRuntimeModule
import org.xtext.CertifiedDjikstraLanguageStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CertifiedDjikstraLanguageIdeSetup extends CertifiedDjikstraLanguageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CertifiedDjikstraLanguageRuntimeModule, new CertifiedDjikstraLanguageIdeModule))
	}
	
}
