/*
 * generated by Xtext 2.22.0
 */
package web.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import web.CertifiedDjikstraLanguageRuntimeModule;
import web.CertifiedDjikstraLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CertifiedDjikstraLanguageIdeSetup extends CertifiedDjikstraLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CertifiedDjikstraLanguageRuntimeModule(), new CertifiedDjikstraLanguageIdeModule()));
	}
	
}
