/*
 * generated by Xtext 2.22.0
 */
package web.ide;


/**
 * Use this class to register ide components.
 */
public class CertifiedDjikstraLanguageIdeModule extends AbstractCertifiedDjikstraLanguageIdeModule {
}
